getwd()
list.files()

library(BiocManager)
library(remotes)
library(TCGAbiolinks)
library(SummarizedExperiment)
library(tidyverse)
library(maftools)
library(DESeq2)
library(EnhancedVolcano)
library(dplyr)
library(ggplot2)
library(ggrepel)

gdc_project = getGDCprojects()
View(gdc_project)
head(gdc_project)
